class_name ReachesLandmarks
extends Node3D
## Red Reaches landmarks, skyline and set dressing built from the Blender kit (ReachesKit) and placed by
## game/world/red_reaches/world_art.json (generated by tools/gen_world_art.py, hand-editable).
## Every group is MERGED into one vertex-coloured mesh per material (one or two draw calls per group, frustum-culled as a
## unit, optional visibility range), solid pieces get cheap box / cylinder colliders on layer 1.
## Group: {id, shadow, vis_end, items:[{p: piece, x, z, y?, r (deg yaw), s (scale), tilt?, col: [sx,sy,sz] box | {"cyl":[r,h]}}]}
##        or a scatter item {scatter:{c:[x,z], r, n, seed, pieces:[..], s:[min,max], off_floor|on_floor, min_gap}}.

const ART_PATH := "res://game/world/red_reaches/world_art.json"

var terrain: Node
var stats := {"tris": 0, "items": 0, "groups": 0}
var _rng := RandomNumberGenerator.new()


func populate(t: Node) -> void:
	terrain = t
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(ART_PATH))
	if not (parsed is Dictionary):
		push_warning("ReachesLandmarks: cannot parse " + ART_PATH)
		return
	for g in (parsed as Dictionary).get("groups", []):
		_build_group(g)
	if OS.get_cmdline_user_args().has("qa"):
		print("[PERF] landmarks groups=%d items=%d tris=%d" % [stats["groups"], stats["items"], stats["tris"]])


func _ground(x: float, z: float, bd: bool = false) -> float:
	if bd and terrain.has_method("surface_height"):
		return terrain.surface_height(x, z)
	return terrain.height_at(x, z) if terrain else 0.0


func _expand(g: Dictionary) -> Array:
	var out: Array = []
	for it in g.get("items", []):
		if it.has("scatter"):
			out.append_array(_scatter(it["scatter"]))
		else:
			out.append(it)
	return out


func _scatter(sc: Dictionary) -> Array:
	var out: Array = []
	_rng.seed = int(sc.get("seed", 1))
	var c: Array = sc["c"]
	var R := float(sc["r"])
	var pieces: Array = sc["pieces"]
	var sr: Array = sc.get("s", [1.0, 1.0])
	var tries := 0
	var placed: Array = []
	var gap := float(sc.get("min_gap", 2.0))
	while out.size() < int(sc["n"]) and tries < int(sc["n"]) * 25:
		tries += 1
		var a := _rng.randf() * TAU
		var d := sqrt(_rng.randf()) * R
		var x := float(c[0]) + cos(a) * d * float(sc.get("ax", 1.0))
		var z := float(c[1]) + sin(a) * d
		var sdf: float = terrain.floor_sdf(x, z)
		if sc.get("off_floor", false) and sdf < float(sc.get("floor_margin", 2.5)):
			continue
		if sc.get("on_floor", false) and sdf > -float(sc.get("floor_margin", 1.5)):
			continue
		if _near_marker(x, z, float(sc.get("clear", 3.0))):
			continue
		var ok := true
		for q in placed:
			if Vector2(x - q.x, z - q.y).length() < gap:
				ok = false
				break
		if not ok:
			continue
		placed.append(Vector2(x, z))
		out.append({"p": pieces[_rng.randi() % pieces.size()], "x": x, "z": z, "r": _rng.randf() * 360.0,
			"s": _rng.randf_range(float(sr[0]), float(sr[1]))})
	return out


func _near_marker(x: float, z: float, r: float) -> bool:
	var lay: Dictionary = terrain.layout
	for k in lay.get("markers", {}):
		var m: Array = lay["markers"][k]
		if Vector2(x - float(m[0]), z - float(m[2])).length() < r:
			return true
	for tr in lay.get("triggers", []):
		var p: Array = tr["pos"]
		if Vector2(x - float(p[0]), z - float(p[2])).length() < r:
			return true
	return false


func _build_group(g: Dictionary) -> void:
	var items := _expand(g)
	if items.is_empty():
		return
	var parts: Array = []
	var gnode := Node3D.new()
	gnode.name = "LM_" + str(g.get("id", "group"))
	add_child(gnode)
	for it in items:
		var piece: String = it["p"]
		var m := ReachesKit.mesh(piece)
		if m == null:
			continue
		var x := float(it["x"])
		var z := float(it["z"])
		var y: float = float(it["y"]) if it.has("y") else _ground(x, z, bool(it.get("bd", false)))
		y += float(it.get("dy", 0.0))
		var s := float(it.get("s", 1.0))
		var b := Basis(Vector3.UP, deg_to_rad(float(it.get("r", 0.0))))
		if it.has("tilt"):
			var tl: Array = it["tilt"]
			b = b * Basis.from_euler(Vector3(deg_to_rad(float(tl[0])), 0.0, deg_to_rad(float(tl[1]))))
		var sx: float = s * float(it.get("sx", 1.0))
		var sy: float = s * float(it.get("sy", 1.0))
		b = b.scaled(Vector3(sx, sy, s * float(it.get("sz", 1.0))))
		var xf := Transform3D(b, Vector3(x, y, z))
		parts.append({"mesh": m, "xf": xf})
		stats["items"] += 1
		if it.has("col"):
			_collider(gnode, xf, it["col"])
	var mesh := merge(parts)
	if mesh == null:
		return
	stats["groups"] += 1
	for si in mesh.get_surface_count():
		stats["tris"] += mesh.surface_get_array_index_len(si) / 3
	var mi := MeshInstance3D.new()
	mi.name = "Mesh"
	mi.mesh = mesh
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_ON if g.get("shadow", true) else GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	var ve := float(g.get("vis_end", 0.0))
	if ve > 0.0:
		mi.visibility_range_end = ve
		mi.visibility_range_end_margin = ve * 0.1
		mi.visibility_range_fade_mode = GeometryInstance3D.VISIBILITY_RANGE_FADE_DISABLED
	var vb := float(g.get("vis_begin", 0.0))
	if vb > 0.0:
		mi.visibility_range_begin = vb
	gnode.add_child(mi)


func _collider(parent: Node3D, xf: Transform3D, col: Variant) -> void:
	var sb := StaticBody3D.new()
	sb.collision_layer = 1
	sb.collision_mask = 0
	var cs := CollisionShape3D.new()
	var off := Vector3.ZERO
	if col is Dictionary:
		var cy: Array = col["cyl"]
		var sh := CylinderShape3D.new()
		sh.radius = float(cy[0]) * xf.basis.get_scale().x
		sh.height = float(cy[1]) * xf.basis.get_scale().y
		cs.shape = sh
		off = Vector3(float(col.get("ox", 0.0)), float(cy[1]) * 0.5 + float(col.get("oy", 0.0)), float(col.get("oz", 0.0)))
	else:
		var a: Array = col
		var sh := BoxShape3D.new()
		sh.size = Vector3(float(a[0]), float(a[1]), float(a[2])) * xf.basis.get_scale()
		cs.shape = sh
		off = Vector3(float(a[3]) if a.size() > 3 else 0.0, float(a[1]) * 0.5 + (float(a[4]) if a.size() > 4 else 0.0), float(a[5]) if a.size() > 5 else 0.0)
	sb.transform = Transform3D(xf.basis.orthonormalized(), xf.origin)
	cs.position = off * xf.basis.get_scale()
	sb.add_child(cs)
	parent.add_child(sb)


## Merge transformed kit meshes into one ArrayMesh (one surface per distinct material). Static helper (also used by tools).
static func merge(parts: Array) -> ArrayMesh:
	var acc: Dictionary = {}     # Material -> {v,n,c,uv,idx}
	for p in parts:
		var m: Mesh = p["mesh"]
		var xf: Transform3D = p["xf"]
		var nb := xf.basis.inverse().transposed()
		for s in m.get_surface_count():
			var arr := m.surface_get_arrays(s)
			var mat: Material = m.surface_get_material(s)
			if not acc.has(mat):
				acc[mat] = {"v": PackedVector3Array(), "n": PackedVector3Array(), "c": PackedColorArray(), "uv": PackedVector2Array(), "idx": PackedInt32Array()}
			var a: Dictionary = acc[mat]
			var vs: PackedVector3Array = arr[Mesh.ARRAY_VERTEX]
			var ns: PackedVector3Array = arr[Mesh.ARRAY_NORMAL]
			var cs := PackedColorArray()
			if arr[Mesh.ARRAY_COLOR] != null:
				cs = arr[Mesh.ARRAY_COLOR]
			var uvs := PackedVector2Array()
			if arr[Mesh.ARRAY_TEX_UV] != null:
				uvs = arr[Mesh.ARRAY_TEX_UV]
			var idx: PackedInt32Array = arr[Mesh.ARRAY_INDEX]
			var av: PackedVector3Array = a["v"]
			var an: PackedVector3Array = a["n"]
			var ac: PackedColorArray = a["c"]
			var au: PackedVector2Array = a["uv"]
			var ai: PackedInt32Array = a["idx"]
			var base := av.size()
			var n := vs.size()
			var tv := PackedVector3Array()
			var tn := PackedVector3Array()
			tv.resize(n)
			tn.resize(n)
			for i in n:
				tv[i] = xf * vs[i]
				tn[i] = (nb * ns[i]).normalized()
			av.append_array(tv)
			an.append_array(tn)
			if cs.size() == n:
				ac.append_array(cs)
			else:
				var wc := PackedColorArray()
				wc.resize(n)
				wc.fill(Color.WHITE)
				ac.append_array(wc)
			if uvs.size() == n:
				au.append_array(uvs)
			else:
				var wu := PackedVector2Array()
				wu.resize(n)
				au.append_array(wu)
			var ti := PackedInt32Array()
			ti.resize(idx.size())
			for i in idx.size():
				ti[i] = idx[i] + base
			ai.append_array(ti)
			a["v"] = av
			a["n"] = an
			a["c"] = ac
			a["uv"] = au
			a["idx"] = ai
	if acc.is_empty():
		return null
	var am := ArrayMesh.new()
	for mat in acc:
		var a: Dictionary = acc[mat]
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = a["v"]
		arrays[Mesh.ARRAY_NORMAL] = a["n"]
		arrays[Mesh.ARRAY_COLOR] = a["c"]
		arrays[Mesh.ARRAY_TEX_UV] = a["uv"]
		arrays[Mesh.ARRAY_INDEX] = a["idx"]
		am.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		am.surface_set_material(am.get_surface_count() - 1, mat)
	return am
