#!/usr/bin/env python3
"""Field Codex content (Lead). Every entry paraphrases or quotes the Lore Bible v12. Writes game/canon/codex.json."""
import json, os
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "game", "canon", "codex.json")
E = {}
def add(i, cat, title, body, sub="", portrait="", unlock="found"):
    E[i] = {"category": cat, "title": title, "subtitle": sub, "body": body, "portrait": portrait, "unlock": unlock}

# --- Species
add("species_skitter_mite", "species", "Skitter Mite", "Rust-red mites that strip mineral crust from Red Reaches rock. Harmless alone. Not alone, usually.\n\nBEHAVIOUR: Swarms. When a swarm is broken, the survivors scatter.\n\nHABITAT CHAIN: Reach soil bed · Moss bed · Heat lamp · Scale Anchor.", "WILDLIFE · Red Reaches")
add("species_plate_beetle", "species", "Plate Beetle", "A slow, heavy grazer of mineral lichen with a carapace like layered slate. Normally docile.\n\nFIELD NOTE: Resonance vibration from Dominion survey pylons agitates the nervous ganglia under the carapace. Remove the source and the herd calms.\n\nHABITAT CHAIN: Reach soil bed · Lichen mat · Heat lamp · Scale Anchor.", "WILDLIFE · Red Reaches")
add("species_dust_grazer", "species", "Dust Grazer", "Long-legged lichen grazers that drift across the plateaus in loose herds.\n\nECOLOGY: Their droppings seed the lichen that binds plateau soil. Remove the herd and the valley floor begins to blow away. A keystone species.\n\nHABITAT CHAIN: Reach soil bed · Lichen mat · Humidity mister · Scale Anchor.", "WILDLIFE · KEYSTONE · Red Reaches")
add("species_dominion_drone", "species", "Survey Drone", "Autonomous survey and security drone operating under a Dominion extraction permit. Fast, fragile, and armed with a three-shot burst.\n\nWEAKNESS: Heavy impact.", "DOMINION ASSET")
add("species_augur_rig", "species", "AUGUR-7 Deepcore Rig", "A Thoughtstone extraction rig. Its tuning field resonated with the Ochre Span's foundation and the plate beetles' nervous systems alike.\n\nWhen overheated, it vents coolant through three exposed vents.", "DOMINION ASSET · Permit 7-K")

# --- Characters
add("char_aruun", "characters", "Aruun — The Reacher", "BRU-004 · Homeland: The Red Reaches · Knack: Psionic Bond / Kinetic Force.\n\nA Spanwright apprentice turned warrior. During the Red Span disaster he anchored his bonded Thoughtstone mace, Morrow, and carried part of a bridge for eleven minutes. Thousands escaped. Hundreds did not.\n\nHe is famous for destruction and wants to be remembered for building. He refuses to call Morrow property.\n\n\"Further than you think.\"", "First Ten", "aruun")
add("char_cigarra", "characters", "Cigarra — The Oracle Hopper", "PSI-017 · Homeland: The Canopy Fold · Knack: Probability Perception.\n\nRaised among the Listening Houses, Cigarra perceives outcomes that have not happened — as noise, not clarity. She let humans classify her as a specimen for months while she learned their language. Then she wrote: I KNOW WHAT YOU ARE DOING.\n\nShe refuses to be called an oracle. \"A future seen is a future touched.\"", "First Ten", "cigarra")
add("char_mara", "characters", "Dr. Mara Venn", "Lead physicist and expedition lead. One of the intellectual architects of the Stewardship Coalition, though she dislikes being a symbol.\n\nPrinciple: access does not create ownership.\n\n\"Curiosity always wins. It just usually costs more than people expect.\"", "Stewardship Coalition", "mara")
add("char_dexter", "characters", "Dexter Mane", "Scientist, strategist, expedition architect — and the central figure of the Human Dominion.\n\nHe is not a sadist. He believes humanity has been handed the most consequential discovery in its history, and that hesitation may be more immoral than exploitation. He can be right about facts while catastrophically wrong about what those facts permit.\n\n\"Morality is a luxury. So is time.\"", "Human Dominion", "dexter")
add("char_mollusk", "characters", "Mollusk — The Weight of Tomorrow", "CHR-001 · Homeland: Rainward · Knack: Temporal Inertia.\n\nMollusk does not stop time; he increases resistance to change. Rescue crews love him. He teaches a doctrine called Borrowed Seconds: every second he creates is a debt. Use it.\n\nHis love of forklifts remains inexplicable and unquestioned.", "First Ten", "mollusk")
add("char_bramvex", "characters", "Bramvex — The Quiet Command", "MIL-006 · Homeland: Thornmarch · Knack: Camouflage / Sensory Adaptation.\n\nA sergeant, not a legend. Captured, he observed for nineteen days, escaped on the twentieth, freed seventeen detainees — and occupied a Habitat wing until most of his demands quietly became policy.\n\nHis thorned weapon is called Diplomacy.", "First Ten", "bramvex")
add("char_nerit", "characters", "Nerit — The Lumen Weaver", "LUX-031 · Homeland: The Lumen Depths · Knack: Light Relocation / Darkness Manipulation.\n\nIn Nerit's culture darkness can mean privacy, rest, mourning, protection. Nerit argues that darkness can be a right — an argument now shaping Terrarium privacy standards.", "First Ten", "nerit")
add("char_zephyr", "characters", "Zephyr — The Nectar Seeker", "AER-009 · Homeland: The Briarwild · Knack: Motion / Pollination.\n\nIn the Briarwild a spoken promise is contract, reputation and identity. Zephyr loves loopholes and despises broken vows. Officially designated COOPERATIVE NON-DETAINED ENTITY. Someone changed it to CONSULTANT. No one admits doing it.", "First Ten", "zephyr")
add("char_nyxaris", "characters", "Nyxaris — The Frostbloom Weaver", "CRYO-022 · Homeland: Frostbloom · Knack: Cryogenic Silk / Venom.\n\nHer silk patterns encode authorship, warning and family history. Helix Industries called it secretion and patented an imitation. Nyxaris asked: Who gave you permission? Nyxaris v. Helix is still before the courts.", "First Ten", "nyxaris")
add("char_pharilux", "characters", "Pharilux — The Watcher Below", "Designation: UNKNOWN · Homeland: Unknown.\n\nA custodian of thresholds: shores, ruins, places where histories meet. An authenticated photograph from 1897 appears to show him beside lighthouse keepers. Shown modern Gate technology, he said: \"You finally rebuilt it.\"", "First Ten", "pharilux")
add("char_solmara", "characters", "Solmara — The Tide Balancer", "TID-001 · Homeland: The Pelagic Expanse · Knack: Solar / Lunar / Tidal / Gravitational.\n\nSolmara's people experience astronomy through the body before mathematics. On first seeing Earth's Moon, Solmara asked: \"Who moved it?\"", "First Ten", "solmara")
add("char_scarlith", "characters", "Scarlith — The Fermented Kingpin", "MYC-013 · Homeland: The Velvet Warrens · Knack: Fermentation / Decomposition / Cultivation.\n\nTwelve centimetres tall. One of the Undermarket's most capable brokers. \"Value begins where neglect ends — but neglect must be real.\"", "First Ten", "scarlith")

# --- Places
add("place_terrarium_one", "places", "Terrarium One", "It began as a secure Gate complex. Every new Habitat added machinery; then the environments began interacting. Spores entered ventilation. A maintenance corridor became a market.\n\nIt stopped being a laboratory containing ecosystems. It became an ecosystem containing laboratories.")
add("place_the_common", "places", "The Common", "The first genuinely mixed district. No architect designed it. At its centre stands the Common Table, built from discarded Habitat material. Nobody officially owns it.")
add("place_red_reaches", "places", "The Red Reaches", "Plateaus, mineral deserts and enormous fracture valleys. Settlements survive because generations maintain bridges, wells and roads. Reach culture is built on carried weight: strength is the burden you can accept without forcing it onto someone weaker.")
add("place_ochre_span", "places", "The Ochre Span", "A Spanwright crossing older than anyone's records, built in the same tradition as the Red Span. Every keystone carries the next.")
add("place_gate", "places", "Scale Transition Array (the Gate)", "A Gate forces matter into a stable relationship with another scale-state. Earth is S0. Critter is S−1. \"Shrinking\" is convenient slang and scientifically incomplete.")

# --- Lore
add("old_roads", "lore", "The Old Roads", "Ruined causeways. Abandoned migration tunnels. Stone markers whose symbols appear continents apart. Dead trade languages.\n\nThey do not prove a lost global empire. They prove that Critter's civilizations have risen, connected, fragmented and forgotten one another many times.")
add("lore_tilt", "lore", "Scale Sickness — the Tilt", "Crossing is physically stressful: vertigo, distorted depth perception, phantom changes in body size, auditory delay. Handlers call the first minutes after a rough transition the Tilt.")
add("lore_knacks", "lore", "Knacks", "A Knack is the human term for an extraordinary biological capability. Knacks are not a universal magic system. They have mechanisms, and they have costs: heat, minerals, hydration, neural stability, time.")
add("lore_capture_law", "lore", "Capture Law", "Wild Containment — dangerous nonsapient organisms.\nProtective Extraction — rescue, medicine, ecological crisis.\nContract Bonding — voluntary partnership between a sapient Critter and a Handler.\nDiplomatic Transit — sapient travellers crossing independently.\nCriminal Extraction — trafficking.\n\nThe technology looks similar. The meaning is completely different.")
add("lore_habitats", "lore", "Habitats", "A captured organism cannot simply be caged. It needs pieces of home: soil chemistry, microbes, humidity, light cycle, pressure, food web, symbionts and a tuned Scale Anchor. Habitats are medical infrastructure.")
add("lore_burden_architecture", "lore", "Burden Architecture", "Aruun's engineering school: design structures around distributed failure. If one section breaks, the rest survives. \"A structure should sacrifice itself before it sacrifices the people inside it.\"")
add("lore_human_schism", "lore", "The Human Schism", "The Stewardship Coalition: Access does not create ownership.\nThe Human Dominion: A frontier ignored is a frontier surrendered.\n\nNeither is a government. Their beliefs cut through every institution.")

# --- Mysteries
add("mystery_thoughtstone", "mysteries", "Thoughtstone", "Grows around deep subterranean biological-mineral networks. Most appears inert. Rare pieces respond to neural activity. Samples near Morrow align their internal structure toward it.\n\nIs it mineral, organism, network, memory medium — or something without a human category?", "OPEN")
add("mystery_eightfold", "mysteries", "The Eightfold Paradox", "How can a world entered by descending in scale contain more internal space than the world from which the traveller descended? Critter is roughly eight times Earth's size. Several models compete. None is confirmed.", "OPEN")
add("mystery_pharilux_1897", "mysteries", "The 1897 Problem", "An authenticated Earth photograph, predating modern Quantum Descent, appears to show Pharilux beside lighthouse keepers. The markings match. The damaged lens matches.", "OPEN")
add("mystery_moon", "mysteries", "The Moon Question", "Solmara: the Moon is not in the wrong orbit. The relationship feels displaced. Earth's gravitational pattern contains a missing return. No instrument has yet detected what that means.", "OPEN")

json.dump({"entries": E}, open(OUT, "w"), indent=1, ensure_ascii=False)
print(len(E), "codex entries")
