"""Measured landmarks, materials, questions, style, review notes for the remaining characters (fractions of silhouette height, top=0, sole=1)."""
L = lambda **k: k
EXTRA = {}

EXTRA["mara"] = dict(
 lm={"front": L(top=0, crown=.015, eyes=.09, chin=.145, neck=.165, shoulder=.195, elbow=.385, wrist=.50, waist=.40, crotch=.56, knee=.70, ankle=.91, ground=1),
     "side": L(top=0, crown=.015, eyes=.095, chin=.15, neck=.175, shoulder=.20, elbow=.40, wrist=.52, waist=.40, crotch=.56, knee=.70, ankle=.91, ground=1),
     "back": L(top=0, crown=.02, eyes=.10, chin=.17, neck=.19, shoulder=.215, elbow=.40, wrist=.53, waist=.40, crotch=.55, knee=.70, ankle=.91, ground=1)},
 lm_src="READ off the gridded art (+-1.5%). Hair bun counts toward height (bun top = 'top').",
 callout_panel="expr_neutral",
 callouts={"eyes": (.25, .28, .80, .50), "nose + freckles": (.30, .45, .75, .66), "mouth": (.30, .62, .75, .80)},
 view_details={"hand_front": ("front", .55, .46, .95, .60), "hand_side": ("side", .55, .45, .98, .62), "hand_back": ("back", .80, .46, 1.0, .62), "boots_side": ("side", .05, .86, .98, 1.0), "boots_back": ("back", .0, .85, 1.0, 1.0), "backpack_side": ("side", .0, .16, .50, .50), "backpack_back": ("back", .20, .17, .85, .46)},
 material_view="side",
 materials=[dict(name="Hair (dark brown)", cls="hair", sample=("side", .62, .04), rough=.6, metal=0, note="messy high bun, loose strands"), dict(name="Skin (warm light brown)", cls="skin", sample=("side", .80, .115), rough=.5, metal=0, note="freckles + scar on LEFT cheek are paint"),
   dict(name="Jumpsuit (grey-beige)", cls="cloth (ripstop)", sample=("side", .55, .50), rough=.85, metal=0, note="expedition jumpsuit; trousers bloused over boots"), dict(name="Black harness / pads / pack", cls="nylon + moulded plastic", sample=("side", .55, .75), rough=.7, metal=0, note="knee pads rough .5; straps webbing .9"),
   dict(name="Backpack accent strips", cls="painted plastic", sample=("side", .02, .29), rough=.5, metal=0, note="orange strips (#d9803a-like) on the Expedition Pack"), dict(name="Boots", cls="leather + rubber sole", sample=("side", .55, .965), rough=.6, metal=0, note="black lace-up combat boots"),
   dict(name="Gloves (black)", cls="leather/fabric", sample=("side", .74, .54), rough=.7, metal=0, note="fingerless look"), dict(name="Stewardship patch", cls="embroidered patch", sample=("side", .38, .27), rough=.9, metal=0, note="dark disc, white emblem, LEFT shoulder")],
 layers=["Skin", "Grey-beige jumpsuit", "Black upper-arm bands, gloves, knee pads", "Black harness straps (chest, waist, thighs) + utility belt/pouches", "Stewardship patch (left shoulder)", "Expedition Pack (largest layer, back)", "Boots over bloused trouser cuffs"],
 expressions=["neutral", "curious", "focused", "annoyed", "tired", "soft"],
 style=dict(line="Clean medium-heavy black ink contour, thinner on folds; slightly warm-brown line on the face.", color="Neutral muted blocks: grey-beige suit, black gear, warm brown skin/hair, small orange accents; palette strip on the sheet: black, charcoal, grey, olive, dark green, orange, blue.", shading="Flat cel, one soft shadow tone; face has a light blush gradient and freckles.", shape="Athletic, upright, narrow; the big rectangular backpack is the signature silhouette element. Bloused trousers over boots make a pronounced ankle bulge.", locks=["Messy high bun with loose strands", "Freckles across nose/cheeks; small scar on LEFT cheek", "Grey-beige jumpsuit + black harness + round patch left shoulder", "Large black pack with orange strips", "Black knee pads, boots, fingerless-look gloves", "170 cm"]),
 questions=["The sheet's FRONT turnaround figure is a 3/4 turn, not a flat front (its twin is the side). Please supply or approve a true orthographic front (face symmetry, harness layout on the chest).",
   "Hair: the bun's volume differs between views (side wider than front). Which silhouette is canon?", "Tattoo (forearm, 'minimal personal meaning') appears only in a detail panel: model it? Which arm?", "Helmet / field tablet / watch props exist as sheet panels (details/): in-game props or cut-scene only?", "Scar/freckles: bake into texture only (assumed)."],
 review=["Turnaround figures are small on the sheet (about 85 px wide) so the x4 views are smooth but soft; line weight is consistent.", "FRONT is a 3/4 turn (flagged non-ortho). Back is truly frontal; side is truly lateral.", "Photoreal concept images in the lore bible (image5/6) are a different style and were NOT used."])

EXTRA["dexter"] = dict(
 lm={"front": L(top=0, crown=.0, eyes=.07, chin=.115, neck=.13, shoulder=.155, elbow=.33, wrist=.43, waist=.37, crotch=.52, knee=.72, ankle=.93, ground=1),
     "back": L(top=0, crown=.0, eyes=.06, chin=.12, neck=.14, shoulder=.19, elbow=.39, wrist=.52, waist=.40, crotch=.55, knee=.78, ankle=.92, ground=1)},
 lm_src="READ (+-2%). Coat hides crotch/knee in the back view; front crotch/knee from the trousers.",
 callout_panel="detail_eyes", callouts={"eye (grey-green)": (.05, .10, .95, .90)},
 view_details={"boots_front": ("front", .15, .86, 1.0, 1.0), "boots_back": ("back", .05, .86, .95, 1.0), "coat_back_lining": ("back", .05, .12, .95, .60), "hand_pocket_front": ("front", .0, .30, .40, .50), "shoulder_sigil_front": ("front", .0, .08, .40, .25)},
 material_view="front",
 materials=[dict(name="Hair (dark, grey streak right)", cls="hair", sample=("front", .5, .0), rough=.6, metal=0, note="tousled, swept back; streak is paint"), dict(name="Skin (warm tan)", cls="skin", sample=("front", .55, .06), rough=.5, metal=0, note="stubble beard, scar above RIGHT brow"),
   dict(name="Long field coat (black)", cls="cloth (heavy wool/canvas)", sample=("front", .1, .55), rough=.85, metal=0, note="collar up, sleeves pushed to forearm"), dict(name="Coat lining (Dominion red)", cls="cloth (satin-ish)", sample=("back", .50, .70), rough=.55, metal=0, note="whole lining panel, very visible from the back; red sigil"),
   dict(name="Shirt / trousers (black)", cls="cloth", sample=("front", .60, .22), rough=.8, metal=0, note="black shirt, utility trousers"), dict(name="Utility belt + pouches + holster", cls="leather / nylon", sample=("front", .55, .30), rough=.6, metal=0, note="thigh holster with sidearm (metal parts rough .35 metal .8)"),
   dict(name="Boots", cls="leather + rubber", sample=("front", .5, .96), rough=.6, metal=0, note="black lace-up, red sigil on the heel strap")],
 layers=["Skin", "Black shirt + ID lanyard (red cord)", "Trousers + utility belt + thigh holster", "Boots", "Long black coat with red lining (outer)", "Sigil on left shoulder (red)", "Gloves (back view)"],
 expressions=["neutral", "amused", "irritated", "serious", "genuine", "tired"],
 style=dict(line="Heavy black ink, thicker than Mara's; hatching on the face.", color="Near-black everything with ONE colour accent: Dominion red (lining, sigils); skin warm tan; grey streak in hair.", shading="Flat cel with deep shadow tone; faces slightly more painterly (stubble shading).", shape="Tall, lean, vertical: long coat creates a narrow column; broad collar; heavy boots.", locks=["Black long coat, collar up, sleeves pushed up", "Red lining + sigil, red sigil left shoulder", "Grey streak in hair on the right side of the parting; stubble; scar above right brow", "Cigarette", "185 cm"]),
 questions=["There is NO side view and the only front is a 3/4 hero pose with hands in pockets. A true front + side orthographic from the creator are needed before 3D. The greybox cannot be built (needs side+back silhouettes).",
   "Three BACK variants exist (long coat with red lining = hero; jacket + harness; plain long coat). Is the jacket/harness version a separate outfit (casual/lab) to be modelled?", "Lab-coat outfit (white coat over black) is shown in the sheet: separate costume skin?", "Sidearm 'custom non-lethal/lethal' is shown as a panel only: proportions assumed from the panel (gear_sidearm).", "Tattoo (left ribs, faction symbol): model as texture only?"],
 review=["Front head was cut off in the older hires; re-cut includes the head. The neighbouring lab-coat figure's sleeve touches the front figure on the right; removed by component filtering.", "Back view silhouettes are 4 small figures; the biggest (hero back, ~230 px) used. Landmarks inside the coat are guesses (flagged +-2%)."])

EXTRA["zephyr"] = dict(
 lm={"front": L(top=0, crown=.09, eyes=.235, chin=.30, neck=.32, shoulder=.35, elbow=.53, wrist=.64, waist=.52, crotch=.65, knee=.80, ankle=.92, ground=1),
     "side": L(top=0, crown=.10, eyes=.19, chin=.27, neck=.285, shoulder=.315, elbow=.50, wrist=.60, waist=.50, crotch=.66, knee=.80, ankle=.92, ground=1),
     "back": L(top=0, crown=.15, eyes=.21, chin=.28, neck=.305, shoulder=.335, elbow=.50, wrist=.60, waist=.50, crotch=.66, knee=.80, ankle=.91, ground=1)},
 lm_src="READ (+-2%). Zephyr is digitigrade/bird-like and cloaked: 'knee' = the visible leg joint, 'crotch' = hem of the belt/cloak panels. Top = tip of the crest feather.",
 head_panels=["head_1", "head_2", "head_3", "head_4"], callout_panel="head_1", callouts={"eye + mask": (.30, .35, .75, .70), "proboscis base": (.30, .60, .70, .98), "crest + antenna": (.10, .0, .95, .35)},
 view_details={"foot_front": ("front", .05, .88, .98, 1.0), "foot_side": ("side", .25, .88, .75, 1.0), "feet_back": ("back", .0, .86, .75, 1.0), "hand_spear_front": ("front", .0, .60, .30, .85), "vial_belt_front": ("front", .45, .50, .75, .70), "vial_belt_side": ("side", .05, .48, .30, .66), "head_front": ("front", .15, .0, .65, .32)},
 material_view="side",
 materials=[dict(name="Mask / skull face + proboscis", cls="chitin / bone (matte)", sample=("side", .27, .21), rough=.45, metal=0, note="bird-skull mask, long curved proboscis"), dict(name="Eyes (dark, orange glint)", cls="glass", sample=("side", .305, .19), rough=.05, metal=0, emi=.3, note="orange-yellow glint is painted; suggest tiny emissive only if Q approves"),
   dict(name="Crest feathers (crimson/olive)", cls="feather", sample=("side", .45, .06), rough=.6, metal=0, note="leaf-like pointed feathers"), dict(name="Wings (pink to olive)", cls="translucent membrane", sample=("side", .85, .38), rough=.4, metal=0, note="4 wings, pale spots, dark veins; alpha about .6"),
   dict(name="Cloak strips (tattered)", cls="cloth + dried leaf", sample=("side", .55, .75), rough=.9, metal=0, note="cream/olive/crimson strips"), dict(name="Nectar vials", cls="glass + brass", sample=("side", .38, .57), rough=.1, metal=.3, note="pink liquid glows in art; suggest emissive .6 on the liquid (see Q)"),
   dict(name="Flowers (hibiscus, blossoms)", cls="petal", sample=("side", .55, .25), rough=.7, metal=0, note="pink at throat, orange on shoulders"), dict(name="Limbs / talons", cls="dark chitin", sample=("side", .45, .90), rough=.5, metal=0, note="brown-black, gold bands at joints"), dict(name="Gold trim / bands", cls="aged brass", sample=("side", .52, .52), rough=.35, metal=.8, note="small")],
 layers=["Body (thin chitin limbs, talon feet)", "Belt with vials and brass fittings", "Tattered cloak strips (hip/back)", "Shoulder foliage + flowers + scarf", "Wings (fold down the back like a cloak)", "Head: bird-skull mask, crest, antennae with tassels", "Proboscis spear (weapon)"],
 expressions=["calm", "curious", "focused", "aggressive", "haunted"],
 style=dict(line="Dark brown-black ink, medium weight, broken on foliage; wings have thin black outer edge only.", color="Pink/crimson/olive/orange gradients on wings and cloak against a dark brown body; pink glass accents.", shading="Painterly cel: wing gradients pink to olive; flat dark body.", shape="Tall, thin, hunched bird/insect; huge wing cloak makes a triangle; long antennae loops and proboscis extend the silhouette; digitigrade talon legs.", locks=["Hawk-moth proboscis + bird-skull mask", "Crest of pointed crimson/olive feathers; two drooping antennae ending in red tassels", "4 wings pink-to-olive with pale spots, folded down the back", "Nectar vials on the belt (pink)", "Tattered cloak + flowers", "Height 165 cm"]),
 questions=["Height 165 cm: measured to the crest feather tip (as aligned here) or to the head? The standing body is shorter than the silhouette.", "Wings: front view shows them hanging at rest, side/back show them half open. Which pose is the neutral modelling pose?", "Antenna loops and drooping tassels extend beyond the body: are they rigid or soft (physics)?", "The proboscis also appears as a separate spear/whip prop (equipment panel). Is it the same object as the face proboscis?", "Pink vial liquid: emissive in game?", "FRONT view: the sheet's title banner (cream/black ink) overlaps the figure's upper-left behind the left antenna. It was removed, and the front view's LEFT ANTENNA LOOP + part of the mask edge went with it = RED/unknown in the front view. The side and back views show the antennae (drooping tassels), so is it OK to copy the antenna design from them?"],
 review=["FRONT: the sheet title 'ZEPHYR' overlapped the figure; the title area was erased by hand-defined rectangles (0-21% x 0-26% and 0-30% x 0-6.5% of the cut). Colour-keyed removal (near-black + cream pixels left of the head) also removed the front's left antenna loop: documented RED area. Nothing was redrawn.", "SIDE faces right (mirrored by the sheet already). Landmarks are approximate (+-2%) due to the cloak."])

EXTRA["bramvex"] = dict(
 lm={"front": L(top=0, crown=.075, eyes=.15, chin=.205, neck=.225, shoulder=.255, elbow=.46, wrist=.62, waist=.45, crotch=.60, knee=.78, ankle=.93, ground=1),
     "side": L(top=0, crown=.15, eyes=.205, chin=.27, neck=.30, shoulder=.32, elbow=.47, wrist=.60, waist=.47, crotch=.60, knee=.78, ankle=.93, ground=1),
     "back": L(top=0, crown=.09, eyes=.165, chin=.215, neck=.235, shoulder=.27, elbow=.47, wrist=.60, waist=.46, crotch=.62, knee=.80, ankle=.93, ground=1)},
 lm_src="READ (+-3%). Thin stick-insect body under a banner cloak and wings; the cut tops differ (front/back top = lantern or antenna tip, side top = antenna sweep): 'crown' = hat top.",
 head_panels=["head_study_1", "head_study_2", "head_study_3", "head_study_4"], callout_panel="head_study_2", callouts={"red eye": (.40, .38, .80, .70), "cap + band": (.0, .0, 1.0, .40), "mandible / jaw": (.15, .60, .85, .98)},
 view_details={"lantern_front": ("front", .0, .0, .22, .27), "lantern_back": ("back", .78, .0, 1.0, .25), "banner_back": ("back", .50, .25, .85, .85), "feet_front": ("front", .0, .88, 1.0, 1.0), "feet_back": ("back", .1, .88, .95, 1.0), "belt_front": ("front", .25, .40, .75, .58)},
 material_view="front",
 materials=[dict(name="Bark-brown body (stick insect)", cls="chitin / bark", sample=("front", .38, .85), rough=.7, metal=0, note="thorn spurs on every limb segment"), dict(name="Peaked cap (olive/dark, red band)", cls="cloth", sample=("front", .58, .09), rough=.85, metal=0, note="worn low"),
   dict(name="Olive field jacket", cls="cloth", sample=("front", .45, .38), rough=.9, metal=0, note="crossed chest straps"), dict(name="Banner cloak (crimson, gold chevrons)", cls="cloth", sample=("back", .72, .55), rough=.9, metal=0, note="tattered; restrained red insignia"),
   dict(name="Wing membranes (tan/olive)", cls="membrane", sample=("back", .12, .45), rough=.6, metal=0, note="ragged bat-like, with thorn veins; alpha ~.8"), dict(name="Leather pouches / belt", cls="leather", sample=("front", .5, .43), rough=.6, metal=0, note="many brown pouches"),
   dict(name="Lantern", cls="brass + glass", sample=("front", .06, .13), rough=.35, metal=.7, emi=1.0, note="glows orange-red in the art: emissive suggestion 1.0 (Q)"), dict(name="Red eye", cls="glass", sample=("front", .62, .12), rough=.1, metal=0, emi=.4, note="red; head studies panel")],
 layers=["Stick-insect body with thorn spurs", "Olive field jacket + crossed straps", "Belt with pouches", "Wings (back)", "Crimson banner cloak (hangs from shoulders, over wings)", "Peaked cap + antennae", "Lantern staff / thorned weapon 'Diplomacy'"],
 expressions=[],
 style=dict(line="Heavy irregular black ink, thorn-spiky; broken lines on cloth.", color="Bark browns, olive greens, tan membranes, ONE restrained red (cloak, cap band, eye, lantern glow).", shading="Flat cel with dark browns for depth; gold chevron emblem painted.", shape="Very tall and thin; spindly long limbs with thorns, huge bat wings and banner behind; hat and antennae at top.", locks=["Prickly stick-insect body with thorns on every limb", "Peaked cap with red band, red eye, long red-tipped antennae", "Bat-like ragged wings", "Crimson banner cloak with gold chevron emblem", "Lantern + thorned weapon", "Height 2.3 m unconfirmed"]),
 questions=["Height 2.3 m is NOT printed on the sheet. Confirm. Which point is 'top': antenna tips, lantern, or the cap?", "The sheet's SIDE faces screen-left and has a beige panel remnant behind the antenna; mirrored here to face screen-right (same as other packs). OK?", "No expression panel: should the red-eyed head studies stand in for expressions?", "The thorned weapon 'Diplomacy' appears only in the hero crouch and the gear panel: please confirm length.", "Lantern: emissive (it glows in art)?", "Hero pose is a crouch; the turnaround figures are standing. Modelling pose = standing turnaround (assumed).", "SIDE view: is the large pale cream triangle above the head the raised bat wing (edge-on) or leftover sheet background?"],
 review=["Turnaround figures are about 120 px wide on the sheet; ESRGAN output is smooth but the thorn lines are slightly merged.", "SIDE cut contains a large pale cream triangle above the head: probably the bat wing seen edge-on (it matches the wing studies) but it could be sheet background kept by the segmenter - asked as Q7.", "Landmarks are inexact (+-3%) because the body is a thin frame under cloth."])

_sc = dict(top=0, shoulder=.42, elbow=.60, wrist=.72, waist=.62, crotch=.80, knee=.87, ankle=.95, ground=1)
EXTRA["scarlith"] = dict(
 lm={"front": L(**{**_sc, "crown": .10, "eyes": .26, "chin": .37, "neck": .39}), "side": L(**{**_sc, "crown": .13, "eyes": .30, "chin": .42, "neck": .44, "shoulder": .47}), "back": L(**{**_sc, "crown": .12, "eyes": .30, "chin": .42, "neck": .44, "shoulder": .45})},
 lm_src="APPROXIMATE (+-4%): Scarlith is a round mite with 8 legs, not a biped. 'crown' = hat top, 'shoulder' = fore-leg root, 'crotch'/'knee'/'ankle' = leg segments of the rear legs. Top = lantern hook on the staff. Use for rough scale only.",
 head_panels=["expr_neutral"], callout_panel="expr_neutral", callouts={"eyes (black with gold glints)": (.15, .30, .85, .55), "fur tuft 'moustache'": (.10, .55, .90, .85), "tricorn trim": (.0, .0, 1.0, .30)},
 view_details={"face_front": ("front", .15, .08, .62, .40), "lantern_staff_side": ("side", .0, .0, .35, .45), "cheese_back": ("back", .22, .08, .90, .60), "feet_front": ("front", .0, .80, 1.0, 1.0), "feet_back": ("back", .0, .80, 1.0, 1.0), "feet_side": ("side", .1, .80, 1.0, 1.0)},
 material_view="side",
 materials=[dict(name="Velvet fur (crimson)", cls="fur / velvet", sample=("side", .38, .55), rough=.9, metal=0, note="dense short pile; use fur cards or velvet shader with sheen"), dict(name="Legs (darker red tips)", cls="chitin", sample=("side", .45, .95), rough=.5, metal=0, note="8 short legs"),
   dict(name="Tricorn hat (black, gold trim)", cls="cloth / felt", sample=("side", .20, .20), rough=.85, metal=0, note="gold compass/sun emblem"), dict(name="Coat panels + gold embroidery", cls="cloth", sample=("side", .60, .75), rough=.8, metal=0, note="dark long panels, gold thread"),
   dict(name="Cheese carapace", cls="aged cheese (waxy)", sample=("back", .45, .35), rough=.65, metal=0, note="pale yellow with holes; slightly translucent edges (sss 0.2)"), dict(name="Gold chains, coins, medallions", cls="gold metal", sample=("side", .83, .45), rough=.3, metal=1.0, note="small hanging items"),
   dict(name="Lantern (spores)", cls="brass + glass", sample=("side", .05, .30), rough=.3, metal=.7, emi=1.0, note="glows orange; emissive suggestion"), dict(name="Eyes", cls="glass", sample=("side", .27, .30), rough=.05, metal=0, note="glossy black with gold glints")],
 layers=["Mite body (fur) with 8 legs", "Coat panels", "Chains, coins, medallions, charms", "Cheese carapace / treasure backpack (worn like a shell)", "Tricorn", "Staff/halberd with lantern"],
 expressions=["neutral", "curious", "calculating", "aggressive", "satisfied"],
 style=dict(line="Heavy dark-red/black ink, thick outer silhouette, many overlapping hanging items.", color="Crimson reds + black hat + gold embroidery + pale yellow cheese; very warm palette.", shading="Cel with fur-texture hatching; cheese has painted holes and drips.", shape="Squat, round, heavy; huge backpack and hat make a dome; many dangling tatters; low to the ground.", locks=["Red-velvet-mite body, 8 legs, two small black eyes with gold glints, fur-tuft moustache", "Black tricorn with gold compass/sun emblem", "Huge cheese carapace/backpack with holes", "Gold chains/coins/anchor charms", "12 cm tall (scale-state)"]),
 questions=["12 cm: is that to the hat top, the lantern hook (silhouette top here) or the backpack?", "FRONT turnaround is small and its right side is clipped by the sheet crop / neighbouring figure; the cheese backpack's front-right edge is UNKNOWN (red).", "How many legs are visible/used? 8 (canon) but only ~6 are legible in each view.", "Halberd/staff: part of the model or a separate prop? Length (it is the tallest element)?", "Hero art (larger) is a different 3/4 pose: use for costume detail only?", "Lantern emissive?"],
 review=["Turnaround figures are small (about 130 px wide), so x4 output is soft; the hero art (ortho/scarlith_hero_x4.png) is the better detail source.", "Landmarks are approximate; do not take limb ratios from this pack."])

_so = L(top=0, crown=.10, eyes=.27, chin=.45, neck=.47, shoulder=.49, elbow=.56, wrist=.62, waist=.66, crotch=.70, knee=.78, ankle=.92, ground=1)
EXTRA["solmara"] = dict(
 lm={"front": dict(_so), "side": dict(_so, crown=.12, eyes=.25), "back": dict(_so, crown=.15, eyes=.27)},
 lm_src="NOT ANATOMICAL: a sea spider has no neck/torso/hips. Only top (tip of the sun spikes), core centre ('eyes' = sun/moon core), body underside ('chin') and ground are measured; the other rows are evenly spaced placeholders for leg joints so the views stay aligned. Do not read limb ratios from the chart.",
 head_panels=["head_core", "sun_moon_core"], callout_panel="head_core", callouts={"sun core (gold)": (.20, .10, .60, .60), "moon core (black/white crescent)": (.50, .0, 1.0, .60), "proboscis / beak": (.20, .50, .80, 1.0)},
 view_details={"leg_tips_front": ("front", .0, .70, 1.0, 1.0), "leg_tips_side": ("side", .0, .70, 1.0, 1.0), "core_front": ("front", .15, .05, .70, .50), "core_side": ("side", .0, .0, .60, .50), "core_back": ("back", .10, .05, .90, .50)},
 material_view="front",
 materials=[dict(name="Sun core disc + spikes", cls="emissive gold", sample=("front", .45, .30), rough=.3, metal=.6, emi=3.0, note="glows strongly in art; suggest emissive 3.0 gold (#f0a030-ish), spikes thin emissive"), dict(name="Moon core (black/white crescent)", cls="dark glass / matte", sample=("front", .32, .27), rough=.2, metal=0, emi=.3, note="gravity core; crescent rim white"),
   dict(name="Ivory/bone plates", cls="bone / chitin", sample=("side", .45, .75), rough=.45, metal=0, note="pale ivory plates"), dict(name="Gold edging", cls="gold metal", sample=("front", .27, .70), rough=.3, metal=.9, note="leg plate edging"),
   dict(name="Navy-blue segments", cls="chitin / enamel", sample=("front", .55, .60), rough=.35, metal=.1, note="deep navy leg segments"), dict(name="Tide silk / webbing", cls="translucent silk", sample=("front", .85, .55), rough=.2, metal=0, note="pale blue webbing between legs, alpha ~.4 (anatomy panel)")],
 layers=["Legs (8, jointed) + central tiny body", "Proboscis/beak + head plates", "Sun/moon core assembly above/behind the head (eclipse mechanism)", "Tide silk webbing (seen in anatomy panel)"],
 expressions=["calm", "aggressive", "defensive", "curious", "ritual"],
 style=dict(line="Fine dark-navy ink, thin; delicate over many tiny spikes.", color="Gold + ivory + deep navy on parchment (turnaround) / dark ocean backgrounds; gold glows.", shading="Painterly glow around the sun core; legs have cel rim light in gold.", shape="Huge spindly arch of 8 long legs over a tiny body; radial spikes around the cores; vertical symmetric in front/back.", locks=["True pycnogonid (sea spider) layout: tiny body, 8 very long jointed legs, long beak-like proboscis", "Gold sun disc with radiating spikes paired with black/white crescent moon core", "Ivory/gold plates with navy segments", "5.5 m tall (scale-state)"]),
 questions=["Top view and bottom view exist on the sheet (ortho/solmara_top_x4.png, _bottom_x4.png) but were not aligned: do you want them used for the greybox plan view?", "FRONT/SIDE leg tips are clipped by the panel crop and neighbouring figure on the right; the clipped leg endpoints are UNKNOWN (red).", "5.5 m: height of the body+cores at standing, or the full spike-to-ground silhouette (as measured here)?", "Sun core emissive strength + does it cast light in game?", "Leg count/joint count: the front shows only 6-7 legs clearly; confirm 8 and the joint count per leg (3 vs 4).", "Tide silk: separate translucent mesh or texture only?"],
 review=["Rembg kept the parchment panel background on this dark sheet; fixed with colour-key background removal (alpha edges on the thin spikes are soft).", "Left-bottom corner debris in FRONT (panel frame corner) removed by component filtering where possible.", "Sources are 150-px wide on the sheet; fine spike lines are approximations by the upscaler."])

EXTRA["mollusk"] = dict(
 lm={"front": L(top=0, crown=.02, eyes=.04, chin=.26, neck=.285, shoulder=.315, elbow=.47, wrist=.60, waist=.55, crotch=.75, knee=.85, ankle=.94, ground=1),
     "side": L(top=0, crown=.02, eyes=.045, chin=.27, neck=.29, shoulder=.32, elbow=.47, wrist=.60, waist=.55, crotch=.75, knee=.85, ankle=.94, ground=1),
     "back": L(top=0, crown=.06, eyes=.09, chin=.27, neck=.29, shoulder=.32, elbow=.47, wrist=.60, waist=.55, crotch=.75, knee=.85, ankle=.94, ground=1)},
 lm_src="APPROXIMATE (+-3%): a slug-folk figure under layered tattered garments; 'crown' = eyestalk tips, 'eyes' = stalk eyes, 'chin' = where the slug head blends into the body. Arms/legs are hidden under the garments; rows below the shoulder are estimates.",
 head_panels=["expr_calm"], callout_panel="expr_calm", callouts={"eye stalk + eye": (.15, .0, .85, .30), "mouth / lip groove": (.20, .45, .85, .75), "head skin texture": (.10, .20, .90, .80)},
 view_details={"eyestalks_front": ("front", .30, .0, .85, .20), "feet_front": ("front", .0, .86, 1.0, 1.0), "feet_side": ("side", .0, .86, 1.0, 1.0), "feet_back": ("back", .1, .86, .95, 1.0), "shell_back": ("back", .1, .20, .95, .85), "belt_front": ("front", .15, .45, .85, .65), "sword_side": ("side", .45, .55, 1.0, 1.0)},
 material_view="side",
 materials=[dict(name="Slug skin (tan-orange)", cls="skin / mucous", sample=("side", .27, .15), rough=.35, metal=0, note="moist look; slight wet specular"), dict(name="Eyestalks", cls="skin + glossy eyes", sample=("side", .27, .04), rough=.3, metal=0, note="eyes glossy white/black rough .05"),
   dict(name="Shell (brown spiral, banded)", cls="shell / keratin", sample=("back", .65, .40), rough=.4, metal=0, note="dark brown with cream bands, amber spiral centre"), dict(name="Plants + hibiscus on the shell", cls="foliage / petal", sample=("back", .55, .12), rough=.7, metal=0, note="fern leaves, 2 red hibiscus"),
   dict(name="Tattered garments (orange/red/dark purple)", cls="cloth + moss", sample=("side", .55, .70), rough=.9, metal=0, note="layered strips; moss patches"), dict(name="Boots / feet", cls="leather + moss", sample=("side", .50, .97), rough=.6, metal=0, note="tan/brown wraps"),
   dict(name="Sword / time-relic blade", cls="pale gold metal/bone", sample=("side", .83, .85), rough=.4, metal=.5, note="long pale blade along the back of the leg")],
 layers=["Slug body (tan skin)", "Dark purple trousers/skirt", "Orange/red/cream hanging strips + belt with charms", "Moss + foliage on shoulders", "Shell (back), with plants and flowers on top", "Boots/wraps", "Blade / relics"],
 expressions=["calm", "curious", "focused", "angry", "exertion", "serene"],
 style=dict(line="Heavy irregular dark-brown ink; line breaks in moss and tatters.", color="Earth tones: tan skin, brown/amber shell, olive foliage, red/orange accents, deep purple cloth.", shading="Cel with warm shadow; shell has painted ring bands and glossy highlights.", shape="Tall upright slug body with a huge round shell on the back; eye stalks as the topmost shape; ragged garments spread the silhouette; heavy feet.", locks=["Two long eye stalks with round eyes", "Large spiral shell on the back with plants/flowers", "Layered tattered garments with moss", "Slug skin (no humanoid hair)", "220 cm"]),
 questions=["The bible has 3 Mollusk sheets (images 10, 22, 23) with different looks; this pack uses tools/source_art/mollusk_sheet.png. Which one is canon?", "Height 2.2 m: to the eyestalk tips (as measured) or the head?", "SIDE faces screen-left on the sheet; mirrored to face screen-right here. OK?", "Arms/hands are almost never visible (hidden under garments): no hand model exists. Please supply or approve the hand design.", "Time-relic mace (hero art) and sword (side view): which are in-game props?", "Shell: rigid, or does it wobble with physics (separate bone)?"],
 review=["Cleanest cut of all characters: strong silhouette and flat paint.", "Legs/arms estimated; do not use limb ratios."])

EXTRA["nerit"] = dict(
 lm={"front": L(top=0, crown=.115, eyes=.31, chin=.38, neck=.40, shoulder=.42, elbow=.55, wrist=.66, waist=.60, crotch=.72, knee=.82, ankle=.93, ground=1),
     "side": L(top=0, crown=.115, eyes=.19, chin=.27, neck=.30, shoulder=.33, elbow=.50, wrist=.64, waist=.58, crotch=.72, knee=.82, ankle=.93, ground=1),
     "back": L(top=0, crown=.10, eyes=.17, chin=.20, neck=.21, shoulder=.28, elbow=.45, wrist=.62, waist=.55, crotch=.72, knee=.83, ankle=.93, ground=1)},
 lm_src="READ (+-3%). Slim hooded firefly-folk with a huge translucent lantern abdomen on the back; top = tip of the antenna lures. Hood/cloak hides shoulders and waist. Front view is a 3/4 turn, so its rows are less reliable.",
 head_panels=["head_1", "head_2", "head_3", "head_4"], callout_panel="head_1", callouts={"eye (glowing, pale)": (.30, .25, .90, .60), "antenna + lure": (.10, .0, .90, .35), "mandible / mouth": (.20, .60, .80, .95)},
 view_details={"lantern_back": ("back", .1, .25, .95, .85), "lantern_side_front": ("front", .0, .35, .45, .90), "feet_side": ("side", .1, .88, 1.0, 1.0), "feet_back": ("back", .2, .85, .85, 1.0), "feet_front": ("front", .35, .85, .95, 1.0), "hand_front": ("front", .65, .50, .95, .70), "lures_side": ("side", .0, .0, .50, .30)},
 material_view="side",
 materials=[dict(name="Head carapace (grey-olive)", cls="chitin", sample=("back", .5, .12), rough=.4, metal=0, note="smooth mask-like head, pale glowing eye"), dict(name="Hooded cloak (dark plum)", cls="cloth", sample=("back", .5, .30), rough=.9, metal=0, note="large hood"),
   dict(name="Lantern abdomen", cls="translucent glowing membrane", sample=("back", .5, .55), rough=.15, metal=0, emi=2.0, note="cyan/pink/yellow bioluminescent chambers (the sheet colours differ per view: cyan back, peach front); emissive 2.0, alpha/transmission .6; see Q"), dict(name="Drop lures on antennae", cls="glowing glass", sample=("side", .2, .12), rough=.1, metal=0, emi=1.5, note="teardrop lanterns, pink/green/cyan"),
   dict(name="Skin / limbs (grey-tan)", cls="chitin", sample=("side", .55, .45), rough=.5, metal=0, note="thin limbs"), dict(name="Belts, leather straps, pouches", cls="leather", sample=("side", .62, .52), rough=.6, metal=0, note="brown"), dict(name="Boots", cls="leather", sample=("side", .5, .95), rough=.6, metal=0, note="dark, buckled")],
 layers=["Body (thin grey-tan limbs)", "Trousers + belts + pouches", "Hooded cloak (over shoulders, long back panel)", "Lantern abdomen (back, translucent, glowing)", "Head + antennae with lures", "Hanging lantern charms on belt/cloak"],
 expressions=["neutral", "curious", "calm", "serious", "playful", "unsettling"],
 style=dict(line="Thin dark-brown ink, delicate; lines vanish on glowing parts.", color="Muted plum/olive/tan body against saturated bioluminescent cyan/pink/yellow accents.", shading="Soft cel on cloth; luminous parts painted with gradient glow and white hot cores.", shape="Tall, slim, hooded; the abdomen lantern dominates the back silhouette and the antennae lures arc above the head.", locks=["Antennae with drop lanterns", "Large translucent glowing lantern abdomen on the back", "Hooded plum cloak, belts and hanging lanterns", "Smooth mask-like head with one pale glowing eye per side", "175 cm"]),
 questions=["Front view shows the lantern abdomen peach/yellow; back view shows cyan/pink. Is the glow colour animated/state-based (calm vs charged), or which is the neutral colour?", "FRONT is a 3/4 turn with the abdomen swung to the viewer-left; true neutral abdomen angle in the side view is also tilted. Which pose is neutral?", "175 cm: to the antenna lure tips (measured here) or to the head top?", "SIDE faces screen-left on the sheet; mirrored to face screen-right here. OK?", "Emissive strength + does the lantern cast light in game (design lock for lighting)?", "Hands are only partly visible (front, right hand): need a hand view."],
 review=["Translucent lantern and thin antenna arcs came through background removal; the faint antenna tip lines may lose alpha at 1-px thickness.", "Landmark rows are approximate under the cloak."])

EXTRA["nyxaris"] = dict(
 lm={"front": L(top=0, crown=.30, eyes=.43, chin=.48, neck=.50, shoulder=.54, elbow=.65, wrist=.76, waist=.66, crotch=.78, knee=.86, ankle=.95, ground=1),
     "side": L(top=0, crown=.15, eyes=.42, chin=.50, neck=.52, shoulder=.55, elbow=.66, wrist=.78, waist=.68, crotch=.78, knee=.87, ankle=.95, ground=1),
     "back": L(top=0, crown=.28, eyes=.42, chin=.50, neck=.52, shoulder=.55, elbow=.66, wrist=.76, waist=.68, crotch=.78, knee=.87, ankle=.95, ground=1)},
 lm_src="APPROXIMATE (+-4%): a hunched, multi-legged frost-flower creature; the anatomy is not human so neck/shoulder/crotch rows are placeholders. Top = antenna-lure tip; 'crown' = the base of the petal crest. Do not read limb ratios.",
 head_panels=["head_1", "head_2", "head_3", "head_4"], callout_panel="head_1", callouts={"eyes (dark, red-ringed)": (.25, .30, .80, .55), "mouth / mandibles": (.25, .55, .80, .95), "petal crest": (.0, .0, 1.0, .30)},
 view_details={"antennae_front": ("front", .1, .0, .65, .30), "crest_side": ("side", .0, .08, .70, .45), "crest_back": ("back", .1, .20, .95, .50), "feet_front": ("front", .0, .85, 1.0, 1.0), "feet_side": ("side", .0, .85, 1.0, 1.0), "feet_back": ("back", .0, .85, 1.0, 1.0), "claws_front": ("front", .0, .55, .50, .85)},
 material_view="front",
 materials=[dict(name="Black chitin body", cls="chitin (glossy)", sample=("front", .38, .62), rough=.3, metal=0, note="black with painted pink/orange spot highlights"), dict(name="Petal crest + mantle (pink/blue/white)", cls="translucent petal / frost", sample=("side", .55, .25), rough=.3, metal=0, note="thin, translucent petals; alpha .7; slight subsurface"),
   dict(name="White-grey fur / ruff", cls="fur", sample=("front", .22, .55), rough=.8, metal=0, note="fluffy ruff around the face and legs"), dict(name="Antennae (crimson) + drop buds", cls="chitin / glossy", sample=("front", .56, .10), rough=.35, metal=0, emi=.3, note="fuchsia-like hanging buds"),
   dict(name="Legs (black, blue tips)", cls="chitin", sample=("front", .58, .93), rough=.35, metal=0, note="blue-black pointed tips"), dict(name="Pink drips", cls="frost sap / ice", sample=("side", .93, .75), rough=.2, metal=0, note="hanging pink drips")],
 layers=["Black chitin body and legs", "White-grey fur ruff and leg fur", "Pink/blue petal mantle (back and shoulders)", "Petal crest around the head", "Antennae with hanging buds", "Pink drips"],
 expressions=[],
 style=dict(line="Dark plum-black ink, thin and wiry on petals, heavier on the body.", color="High-contrast: black body against pink, pale blue and white petals; orange/yellow micro-accents.", shading="Cel with translucent gradients on petals; fur painted in flat white-grey shards.", shape="Wide, hunched, heavy: a spiky flower-like crest over a broad four-pointed stance with long drooping antennae; very ragged outline.", locks=["Black chitin body with pink/blue/white frost-petal crest and mantle", "Two long antennae ending in hanging fuchsia-like buds", "White-grey fur ruff", "Multi-legged, pointed black legs with blue tips", "200 cm"]),
 questions=["No expression panel exists on the sheet (head studies only). Are the four head studies the expressions to model, or neutral only?", "Leg count: front shows 4-5 big legs, side shows 3+; confirm 6 or 8 and which are arms.", "SIDE view faces screen-right but its right edge (the far antenna tip and leg) is clipped by the panel border: tip and one leg are UNKNOWN (red).", "200 cm: antenna tip (measured) or crest top?", "Petals: modelled as thin cards with alpha or solid shells?", "Pink drips: part of the model or an FX?"],
 review=["The sheet's ground shadow stays as a thin dark band under the legs (not removed to avoid eating leg tips).", "Heavy overlapping of fur/petals: ESRGAN smoothing merges some thin petal edges.", "Side cut is clipped at the right edge."])

EXTRA["pharilux"] = dict(
 lm={"front": L(top=0, crown=.12, eyes=.19, chin=.27, neck=.30, shoulder=.33, elbow=.50, wrist=.62, waist=.55, crotch=.70, knee=.82, ankle=.93, ground=1),
     "side": L(top=0, crown=.22, eyes=.34, chin=.42, neck=.44, shoulder=.46, elbow=.58, wrist=.66, waist=.60, crotch=.72, knee=.83, ankle=.93, ground=1),
     "back": L(top=0, crown=.20, eyes=.24, chin=.28, neck=.30, shoulder=.34, elbow=.50, wrist=.62, waist=.58, crotch=.74, knee=.85, ankle=.94, ground=1)},
 lm_src="APPROXIMATE (+-4%): hunched moth-lighthouse figure; side view is bent forward (head low at 0.34) so head rows differ strongly per view and the warp there is large. Top = lantern finial / antenna tip.",
 head_panels=["head_1", "head_2", "head_3", "head_4"], callout_panel="head_1", callouts={"eye (glowing amber)": (.25, .25, .80, .60), "antenna base": (.0, .0, 1.0, .30), "mouth": (.25, .60, .80, .95)},
 view_details={"lantern_side": ("side", .50, .0, .98, .35), "lantern_back": ("back", .50, .05, .95, .35), "lamp_pendant_side": ("side", .80, .30, 1.0, .55), "sigil_side": ("side", .45, .38, .75, .55), "feet_front": ("front", .05, .88, .95, 1.0), "feet_side": ("side", .0, .85, .90, 1.0), "feet_back": ("back", .0, .85, 1.0, 1.0)},
 material_view="side",
 materials=[dict(name="Lantern glass (glowing)", cls="emissive glass", sample=("side", .70, .16), rough=.1, metal=0, emi=4.0, note="warm amber; strongest light on the character; suggest point light"), dict(name="Lantern frame + brass fittings", cls="aged copper/brass", sample=("side", .68, .08), rough=.4, metal=.8, note="rust-brown, orange trim"),
   dict(name="Dark cloak / body", cls="cloth + chitin", sample=("side", .55, .75), rough=.8, metal=0, note="charcoal blue-grey with orange stitched/chain lines"), dict(name="Wings (pale grey-cream, tattered)", cls="translucent membrane", sample=("side", .50, .65), rough=.4, metal=0, note="large, torn; alpha .6"),
   dict(name="Head (olive-grey chitin)", cls="chitin", sample=("side", .12, .33), rough=.4, metal=0, emi=.5, note="eyes amber glow painted"), dict(name="Gold sigils / chains / pendant", cls="gold metal", sample=("side", .62, .45), rough=.3, metal=.9, note="circular sigil on the lantern housing; hanging pendant lantern"), dict(name="Talon feet", cls="chitin", sample=("side", .20, .975), rough=.5, metal=0, note="dark with orange claw tips")],
 layers=["Body (chitin, hunched)", "Dark cloak with orange chain/stitch ornament", "Wings (two pairs, hang behind)", "Lighthouse lantern on the back/shoulder (housing + glass)", "Head with antennae", "Hanging pendant lantern + chains"],
 expressions=["calm", "curious", "focused", "aggressive", "watchful"],
 style=dict(line="Dark brown-black ink, medium; fine orange chain lines drawn as thin coloured line, not ink.", color="Charcoal blue-grey and brown with orange/amber glow accents; pale cream wings.", shading="Cel with strong warm glow from the lantern windows (painted, hard edged); metal highlights in orange.", shape="Tall, hunched, top-heavy: a tower-like lantern rises over the shoulder like a lighthouse; ragged wings and cloak hang to the ground; long antennae arc forward.", locks=["Lighthouse lantern with glowing windows carried on the back/shoulder", "Moth-like head with long antennae and glowing amber eyes", "Tattered pale wings", "Dark cloak with orange chain/anchor/sigil ornament", "Hanging pendant lantern", "260 cm"]),
 questions=["Side view is strongly hunched/bent; front and back are upright. What is the neutral modelling posture and the true standing height (260 cm measured to the lantern finial here; to the head if upright it would be much less)?", "FRONT is a 3/4 view with arms raised; BACK is frontal; hands/arms are barely visible in the turnaround. Please confirm the arm design (the front shows thin raised arms ending in claws).", "Lantern: is it rigid on the back (a bone) or a separate swinging prop; does it light the scene (design lock)? Suggested emissive 4.0 + point light.", "Antenna length: back view shows a long arc (about 20% of height); side shows a short thin one. Which is canon?", "Wings: how many (front shows 4 hanging, back 2 large)?", "Cut quality: the side's left antenna tip may be thinned by background removal."],
 review=["All three views are original paint, rembg-cut; the side has the largest head-row warp of any pack (about 12% of height) because of the stooped pose: head crops in head/ are therefore on shared rows but differently posed.", "Landmarks approximate; do not read limb ratios."])
