"""Measured landmarks, materials, questions, style, review notes for the remaining characters (fractions of silhouette height, top=0, sole=1)."""
L = lambda **k: k
EXTRA = {}

EXTRA["mara"] = dict(
 lm={"front": L(top=0, crown=.015, eyes=.09, chin=.145, neck=.165, shoulder=.195, elbow=.385, wrist=.50, waist=.40, crotch=.56, knee=.70, ankle=.91, ground=1),
     "side": L(top=0, crown=.015, eyes=.095, chin=.15, neck=.175, shoulder=.20, elbow=.40, wrist=.52, waist=.40, crotch=.56, knee=.70, ankle=.91, ground=1),
     "back": L(top=0, crown=.02, eyes=.10, chin=.17, neck=.19, shoulder=.215, elbow=.40, wrist=.53, waist=.40, crotch=.55, knee=.70, ankle=.91, ground=1)},
 lm_src="READ off the gridded art (+-1.5%). Hair bun counts toward height (bun top = 'top').",
 callout_panel="expr_neutral",
 callouts={"eyes": (.25, .28, .80, .50), "nose + freckles": (.30, .45, .75, .66), "mouth": (.30, .62, .75, .80)},
 view_details={"hand_front": ("front", .55, .46, .95, .60), "hand_side": ("side", .55, .45, .98, .62), "hand_back": ("back", .80, .46, 1.0, .62), "boots_side": ("side", .05, .86, .98, 1.0), "boots_back": ("back", .0, .85, 1.0, 1.0), "backpack_side": ("side", .0, .16, .50, .50), "backpack_back": ("back", .20, .17, .85, .46)},
 material_view="side",
 materials=[dict(name="Hair (dark brown)", cls="hair", sample=("side", .62, .04), rough=.6, metal=0, note="messy high bun, loose strands"), dict(name="Skin (warm light brown)", cls="skin", sample=("side", .80, .115), rough=.5, metal=0, note="freckles + scar on LEFT cheek are paint"),
   dict(name="Jumpsuit (grey-beige)", cls="cloth (ripstop)", sample=("side", .55, .50), rough=.85, metal=0, note="expedition jumpsuit; trousers bloused over boots"), dict(name="Black harness / pads / pack", cls="nylon + moulded plastic", sample=("side", .55, .75), rough=.7, metal=0, note="knee pads rough .5; straps webbing .9"),
   dict(name="Backpack accent strips", cls="painted plastic", sample=("side", .02, .29), rough=.5, metal=0, note="orange strips (#d9803a-like) on the Expedition Pack"), dict(name="Boots", cls="leather + rubber sole", sample=("side", .55, .965), rough=.6, metal=0, note="black lace-up combat boots"),
   dict(name="Gloves (black)", cls="leather/fabric", sample=("side", .74, .54), rough=.7, metal=0, note="fingerless look"), dict(name="Stewardship patch", cls="embroidered patch", sample=("side", .38, .27), rough=.9, metal=0, note="dark disc, white emblem, LEFT shoulder")],
 layers=["Skin", "Grey-beige jumpsuit", "Black upper-arm bands, gloves, knee pads", "Black harness straps (chest, waist, thighs) + utility belt/pouches", "Stewardship patch (left shoulder)", "Expedition Pack (largest layer, back)", "Boots over bloused trouser cuffs"],
 expressions=["neutral", "curious", "focused", "annoyed", "tired", "soft"],
 style=dict(line="Clean medium-heavy black ink contour, thinner on folds; slightly warm-brown line on the face.", color="Neutral muted blocks: grey-beige suit, black gear, warm brown skin/hair, small orange accents; palette strip on the sheet: black, charcoal, grey, olive, dark green, orange, blue.", shading="Flat cel, one soft shadow tone; face has a light blush gradient and freckles.", shape="Athletic, upright, narrow; the big rectangular backpack is the signature silhouette element. Bloused trousers over boots make a pronounced ankle bulge.", locks=["Messy high bun with loose strands", "Freckles across nose/cheeks; small scar on LEFT cheek", "Grey-beige jumpsuit + black harness + round patch left shoulder", "Large black pack with orange strips", "Black knee pads, boots, fingerless-look gloves", "170 cm"]),
 questions=["The sheet's FRONT turnaround figure is a 3/4 turn, not a flat front (its twin is the side). Please supply or approve a true orthographic front (face symmetry, harness layout on the chest).",
   "Hair: the bun's volume differs between views (side wider than front). Which silhouette is canon?", "Tattoo (forearm, 'minimal personal meaning') appears only in a detail panel: model it? Which arm?", "Helmet / field tablet / watch props exist as sheet panels (details/): in-game props or cut-scene only?", "Scar/freckles: bake into texture only (assumed)."],
 review=["Turnaround figures are small on the sheet (about 85 px wide) so the x4 views are smooth but soft; line weight is consistent.", "FRONT is a 3/4 turn (flagged non-ortho). Back is truly frontal; side is truly lateral.", "Photoreal concept images in the lore bible (image5/6) are a different style and were NOT used."])

EXTRA["dexter"] = dict(
 lm={"front": L(top=0, crown=.0, eyes=.07, chin=.115, neck=.13, shoulder=.155, elbow=.33, wrist=.43, waist=.37, crotch=.52, knee=.72, ankle=.93, ground=1),
     "back": L(top=0, crown=.0, eyes=.06, chin=.12, neck=.14, shoulder=.19, elbow=.39, wrist=.52, waist=.40, crotch=.55, knee=.78, ankle=.92, ground=1)},
 lm_src="READ (+-2%). Coat hides crotch/knee in the back view; front crotch/knee from the trousers.",
 callout_panel="detail_eyes", callouts={"eye (grey-green)": (.05, .10, .95, .90)},
 view_details={"boots_front": ("front", .15, .86, 1.0, 1.0), "boots_back": ("back", .05, .86, .95, 1.0), "coat_back_lining": ("back", .05, .12, .95, .60), "hand_pocket_front": ("front", .0, .30, .40, .50), "shoulder_sigil_front": ("front", .0, .08, .40, .25)},
 material_view="front",
 materials=[dict(name="Hair (dark, grey streak right)", cls="hair", sample=("front", .5, .0), rough=.6, metal=0, note="tousled, swept back; streak is paint"), dict(name="Skin (warm tan)", cls="skin", sample=("front", .55, .06), rough=.5, metal=0, note="stubble beard, scar above RIGHT brow"),
   dict(name="Long field coat (black)", cls="cloth (heavy wool/canvas)", sample=("front", .1, .55), rough=.85, metal=0, note="collar up, sleeves pushed to forearm"), dict(name="Coat lining (Dominion red)", cls="cloth (satin-ish)", sample=("back", .50, .70), rough=.55, metal=0, note="whole lining panel, very visible from the back; red sigil"),
   dict(name="Shirt / trousers (black)", cls="cloth", sample=("front", .60, .22), rough=.8, metal=0, note="black shirt, utility trousers"), dict(name="Utility belt + pouches + holster", cls="leather / nylon", sample=("front", .55, .30), rough=.6, metal=0, note="thigh holster with sidearm (metal parts rough .35 metal .8)"),
   dict(name="Boots", cls="leather + rubber", sample=("front", .5, .96), rough=.6, metal=0, note="black lace-up, red sigil on the heel strap")],
 layers=["Skin", "Black shirt + ID lanyard (red cord)", "Trousers + utility belt + thigh holster", "Boots", "Long black coat with red lining (outer)", "Sigil on left shoulder (red)", "Gloves (back view)"],
 expressions=["neutral", "amused", "irritated", "serious", "genuine", "tired"],
 style=dict(line="Heavy black ink, thicker than Mara's; hatching on the face.", color="Near-black everything with ONE colour accent: Dominion red (lining, sigils); skin warm tan; grey streak in hair.", shading="Flat cel with deep shadow tone; faces slightly more painterly (stubble shading).", shape="Tall, lean, vertical: long coat creates a narrow column; broad collar; heavy boots.", locks=["Black long coat, collar up, sleeves pushed up", "Red lining + sigil, red sigil left shoulder", "Grey streak in hair on the right side of the parting; stubble; scar above right brow", "Cigarette", "185 cm"]),
 questions=["There is NO side view and the only front is a 3/4 hero pose with hands in pockets. A true front + side orthographic from the creator are needed before 3D. The greybox cannot be built (needs side+back silhouettes).",
   "Three BACK variants exist (long coat with red lining = hero; jacket + harness; plain long coat). Is the jacket/harness version a separate outfit (casual/lab) to be modelled?", "Lab-coat outfit (white coat over black) is shown in the sheet: separate costume skin?", "Sidearm 'custom non-lethal/lethal' is shown as a panel only: proportions assumed from the panel (gear_sidearm).", "Tattoo (left ribs, faction symbol): model as texture only?"],
 review=["Front head was cut off in the older hires; re-cut includes the head. The neighbouring lab-coat figure's sleeve touches the front figure on the right; removed by component filtering.", "Back view silhouettes are 4 small figures; the biggest (hero back, ~230 px) used. Landmarks inside the coat are guesses (flagged +-2%)."])

EXTRA["zephyr"] = dict(
 lm={"front": L(top=0, crown=.09, eyes=.235, chin=.30, neck=.32, shoulder=.35, elbow=.53, wrist=.64, waist=.52, crotch=.65, knee=.80, ankle=.92, ground=1),
     "side": L(top=0, crown=.10, eyes=.19, chin=.27, neck=.285, shoulder=.315, elbow=.50, wrist=.60, waist=.50, crotch=.66, knee=.80, ankle=.92, ground=1),
     "back": L(top=0, crown=.15, eyes=.21, chin=.28, neck=.305, shoulder=.335, elbow=.50, wrist=.60, waist=.50, crotch=.66, knee=.80, ankle=.91, ground=1)},
 lm_src="READ (+-2%). Zephyr is digitigrade/bird-like and cloaked: 'knee' = the visible leg joint, 'crotch' = hem of the belt/cloak panels. Top = tip of the crest feather.",
 head_panels=["head_1", "head_2", "head_3", "head_4"], callout_panel="head_1", callouts={"eye + mask": (.30, .35, .75, .70), "proboscis base": (.30, .60, .70, .98), "crest + antenna": (.10, .0, .95, .35)},
 view_details={"foot_front": ("front", .05, .88, .98, 1.0), "foot_side": ("side", .25, .88, .75, 1.0), "feet_back": ("back", .0, .86, .75, 1.0), "hand_spear_front": ("front", .0, .60, .30, .85), "vial_belt_front": ("front", .45, .50, .75, .70), "vial_belt_side": ("side", .05, .48, .30, .66), "head_front": ("front", .15, .0, .65, .32)},
 material_view="side",
 materials=[dict(name="Mask / skull face + proboscis", cls="chitin / bone (matte)", sample=("side", .27, .21), rough=.45, metal=0, note="bird-skull mask, long curved proboscis"), dict(name="Eyes (dark, orange glint)", cls="glass", sample=("side", .305, .19), rough=.05, metal=0, emi=.3, note="orange-yellow glint is painted; suggest tiny emissive only if Q approves"),
   dict(name="Crest feathers (crimson/olive)", cls="feather", sample=("side", .45, .06), rough=.6, metal=0, note="leaf-like pointed feathers"), dict(name="Wings (pink to olive)", cls="translucent membrane", sample=("side", .85, .38), rough=.4, metal=0, note="4 wings, pale spots, dark veins; alpha about .6"),
   dict(name="Cloak strips (tattered)", cls="cloth + dried leaf", sample=("side", .55, .75), rough=.9, metal=0, note="cream/olive/crimson strips"), dict(name="Nectar vials", cls="glass + brass", sample=("side", .38, .57), rough=.1, metal=.3, note="pink liquid glows in art; suggest emissive .6 on the liquid (see Q)"),
   dict(name="Flowers (hibiscus, blossoms)", cls="petal", sample=("side", .55, .25), rough=.7, metal=0, note="pink at throat, orange on shoulders"), dict(name="Limbs / talons", cls="dark chitin", sample=("side", .45, .90), rough=.5, metal=0, note="brown-black, gold bands at joints"), dict(name="Gold trim / bands", cls="aged brass", sample=("side", .52, .52), rough=.35, metal=.8, note="small")],
 layers=["Body (thin chitin limbs, talon feet)", "Belt with vials and brass fittings", "Tattered cloak strips (hip/back)", "Shoulder foliage + flowers + scarf", "Wings (fold down the back like a cloak)", "Head: bird-skull mask, crest, antennae with tassels", "Proboscis spear (weapon)"],
 expressions=["calm", "curious", "focused", "aggressive", "haunted"],
 style=dict(line="Dark brown-black ink, medium weight, broken on foliage; wings have thin black outer edge only.", color="Pink/crimson/olive/orange gradients on wings and cloak against a dark brown body; pink glass accents.", shading="Painterly cel: wing gradients pink to olive; flat dark body.", shape="Tall, thin, hunched bird/insect; huge wing cloak makes a triangle; long antennae loops and proboscis extend the silhouette; digitigrade talon legs.", locks=["Hawk-moth proboscis + bird-skull mask", "Crest of pointed crimson/olive feathers; two drooping antennae ending in red tassels", "4 wings pink-to-olive with pale spots, folded down the back", "Nectar vials on the belt (pink)", "Tattered cloak + flowers", "Height 165 cm"]),
 questions=["Height 165 cm: measured to the crest feather tip (as aligned here) or to the head? The standing body is shorter than the silhouette.", "Wings: front view shows them hanging at rest, side/back show them half open. Which pose is the neutral modelling pose?", "Antenna loops and drooping tassels extend beyond the body: are they rigid or soft (physics)?", "The proboscis also appears as a separate spear/whip prop (equipment panel). Is it the same object as the face proboscis?", "Pink vial liquid: emissive in game?", "FRONT view: the sheet's title banner (cream/black ink) overlaps the figure's upper-left behind the left antenna. It was removed, and the front view's LEFT ANTENNA LOOP + part of the mask edge went with it = RED/unknown in the front view. The side and back views show the antennae (drooping tassels), so is it OK to copy the antenna design from them?"],
 review=["FRONT: the sheet title 'ZEPHYR' overlapped the figure; the title area was erased by hand-defined rectangles (0-21% x 0-26% and 0-30% x 0-6.5% of the cut). Colour-keyed removal (near-black + cream pixels left of the head) also removed the front's left antenna loop: documented RED area. Nothing was redrawn.", "SIDE faces right (mirrored by the sheet already). Landmarks are approximate (+-2%) due to the cloak."])

EXTRA["bramvex"] = dict(
 lm={"front": L(top=0, crown=.075, eyes=.15, chin=.205, neck=.225, shoulder=.255, elbow=.46, wrist=.62, waist=.45, crotch=.60, knee=.78, ankle=.93, ground=1),
     "side": L(top=0, crown=.15, eyes=.205, chin=.27, neck=.30, shoulder=.32, elbow=.47, wrist=.60, waist=.47, crotch=.60, knee=.78, ankle=.93, ground=1),
     "back": L(top=0, crown=.09, eyes=.165, chin=.215, neck=.235, shoulder=.27, elbow=.47, wrist=.60, waist=.46, crotch=.62, knee=.80, ankle=.93, ground=1)},
 lm_src="READ (+-3%). Thin stick-insect body under a banner cloak and wings; the cut tops differ (front/back top = lantern or antenna tip, side top = antenna sweep): 'crown' = hat top.",
 head_panels=["head_study_1", "head_study_2", "head_study_3", "head_study_4"], callout_panel="head_study_2", callouts={"red eye": (.40, .38, .80, .70), "cap + band": (.0, .0, 1.0, .40), "mandible / jaw": (.15, .60, .85, .98)},
 view_details={"lantern_front": ("front", .0, .0, .22, .27), "lantern_back": ("back", .78, .0, 1.0, .25), "banner_back": ("back", .50, .25, .85, .85), "feet_front": ("front", .0, .88, 1.0, 1.0), "feet_back": ("back", .1, .88, .95, 1.0), "belt_front": ("front", .25, .40, .75, .58)},
 material_view="front",
 materials=[dict(name="Bark-brown body (stick insect)", cls="chitin / bark", sample=("front", .38, .85), rough=.7, metal=0, note="thorn spurs on every limb segment"), dict(name="Peaked cap (olive/dark, red band)", cls="cloth", sample=("front", .58, .09), rough=.85, metal=0, note="worn low"),
   dict(name="Olive field jacket", cls="cloth", sample=("front", .45, .38), rough=.9, metal=0, note="crossed chest straps"), dict(name="Banner cloak (crimson, gold chevrons)", cls="cloth", sample=("back", .72, .55), rough=.9, metal=0, note="tattered; restrained red insignia"),
   dict(name="Wing membranes (tan/olive)", cls="membrane", sample=("back", .12, .45), rough=.6, metal=0, note="ragged bat-like, with thorn veins; alpha ~.8"), dict(name="Leather pouches / belt", cls="leather", sample=("front", .5, .43), rough=.6, metal=0, note="many brown pouches"),
   dict(name="Lantern", cls="brass + glass", sample=("front", .06, .13), rough=.35, metal=.7, emi=1.0, note="glows orange-red in the art: emissive suggestion 1.0 (Q)"), dict(name="Red eye", cls="glass", sample=("front", .62, .12), rough=.1, metal=0, emi=.4, note="red; head studies panel")],
 layers=["Stick-insect body with thorn spurs", "Olive field jacket + crossed straps", "Belt with pouches", "Wings (back)", "Crimson banner cloak (hangs from shoulders, over wings)", "Peaked cap + antennae", "Lantern staff / thorned weapon 'Diplomacy'"],
 expressions=[],
 style=dict(line="Heavy irregular black ink, thorn-spiky; broken lines on cloth.", color="Bark browns, olive greens, tan membranes, ONE restrained red (cloak, cap band, eye, lantern glow).", shading="Flat cel with dark browns for depth; gold chevron emblem painted.", shape="Very tall and thin; spindly long limbs with thorns, huge bat wings and banner behind; hat and antennae at top.", locks=["Prickly stick-insect body with thorns on every limb", "Peaked cap with red band, red eye, long red-tipped antennae", "Bat-like ragged wings", "Crimson banner cloak with gold chevron emblem", "Lantern + thorned weapon", "Height 2.3 m unconfirmed"]),
 questions=["Height 2.3 m is NOT printed on the sheet. Confirm. Which point is 'top': antenna tips, lantern, or the cap?", "The sheet's SIDE faces screen-left and has a beige panel remnant behind the antenna; mirrored here to face screen-right (same as other packs). OK?", "No expression panel: should the red-eyed head studies stand in for expressions?", "The thorned weapon 'Diplomacy' appears only in the hero crouch and the gear panel: please confirm length.", "Lantern: emissive (it glows in art)?", "Hero pose is a crouch; the turnaround figures are standing. Modelling pose = standing turnaround (assumed).", "SIDE view: is the large pale cream triangle above the head the raised bat wing (edge-on) or leftover sheet background?"],
 review=["Turnaround figures are about 120 px wide on the sheet; ESRGAN output is smooth but the thorn lines are slightly merged.", "SIDE cut contains a large pale cream triangle above the head: probably the bat wing seen edge-on (it matches the wing studies) but it could be sheet background kept by the segmenter - asked as Q7.", "Landmarks are inexact (+-3%) because the body is a thin frame under cloth."])
